name: cheese_shoppe
description: "My project about cheese"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  sqlite3: ^2.4.7
  floor: ^1.5.0
  sqflite: ^2.4.1
  flutter_localizations:
    sdk: flutter
  dartdoc: ^8.1.0
  encrypt_shared_preferences: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  path_provider: ^2.0.0
  build_runner: ^2.4.13
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/translations/
    - assets/cheeses.json
